- .gitlab-ci.yml
Some of CI variables are not being in used atm, but we will need them soon so I just added them there
> PT-126 | Add .gitlab-ci.yml

- graphene_linked_events/schema.py
- occurrences/schema.py
- Venue query should return empty instead of throwing error when object not found
- `p_event` should be empty when it's not created in event query
- Added `venue` to `Event` that returns venue custom data based on event `place_id`
> Fix venue query

- common/utils.py
- graphene_linked_events/schema.py
- graphene_linked_events/tests/mock_data.py
- graphene_linked_events/tests/snapshots/snap_test_api.py
- graphene_linked_events/tests/test_api.py
- occurrences/models.py
- Added mutation to publish event (update `linked_event.publication_status`)
- Add `draft` argument when create event
> PT-340 | Add publish event mutation

- occurrences/schema.py
- occurrences/tests/snapshots/snap_test_api.py
- occurrences/tests/test_api.py
When updating enrolment, some validation should be skipped, some should be validated in a different way
> PT-341 | Fix update enrolment validation

- common/tests/conftest.py
- occurrences/models.py
- occurrences/notifications.py
- occurrences/schema.py
- occurrences/tests/snapshots/snap_test_api.py
- occurrences/tests/snapshots/snap_test_notifications.py
- occurrences/tests/test_api.py
- occurrences/tests/test_notifications.py
Add custom message to email/sms template
Update approve/decline mutation to support passing custom message
> PT-355 | Add custom message to approve/decline mutation

- common/tests/conftest.py
- occurrences/tests/snapshots/snap_test_api.py
- occurrences/tests/test_api.py
- palvelutarjotin/schema.py
Added a graphql query to query template by template type (notification type). The query receive context variable as JSONString argument, then return rendered notification preview
> PT-393 | Add custom context template preview

- occurrences/schema.py
- occurrences/tests/snapshots/snap_test_api.py
- occurrences/tests/test_api.py
Sometimes, client wants to query the linked event data from occurrence (render preview email)
This PR also fixed a small error in the test.
> Add linked event to occurrence query

- common/tests/notification_template_fixtures.py
- occurrences/models.py
- occurrences/notifications.py
- occurrences/tests/snapshots/snap_test_api.py
- occurrences/tests/snapshots/snap_test_notifications.py
- occurrences/tests/test_notifications.py
- occurrences/utils.py
- palvelutarjotin/schema.py
Display occurrence local time in notification
> PT-400 | Localtime template

- occurrences/schema.py
- occurrences/tests/snapshots/snap_test_api.py
- occurrences/tests/test_api.py
Added an endpoint to query enrolments by staff organisation id and status. 
Added `count` field to the connection
> PT-424 | Enrolment summary

- .gitlab-ci.yml
- .prod/uwsgi.ini
- common/tests/notification_template_fixtures.py
- occurrences/consts.py
- occurrences/factories.py
- occurrences/management/commands/send_enrolment_summary.py
- occurrences/models.py
- occurrences/notifications.py
- occurrences/tests/snapshots/snap_test_api.py
- occurrences/tests/snapshots/snap_test_notifications.py
- occurrences/tests/test_notifications.py
- palvelutarjotin/settings.py
User story: https://helsinkisolutionoffice.atlassian.net/secure/RapidBoard.jspa?rapidView=40&projectKey=PT&modal=detail&selectedIssue=PT-544
> PT-554 PT-555 | Daily summary report for provider

- occurrences/models.py
- occurrences/schema.py
- occurrences/tests/snapshots/snap_test_api.py
- occurrences/tests/snapshots/snap_test_notifications.py
- occurrences/tests/test_api.py
- occurrences/tests/test_models.py
Pull reguest for Feature/PT-680. Updated Occurrence model seat count functions and tests related to them. It was also needed to update test-snapshots.
> Amount of adults is added to calculation when counting taken or approved seats.

- templates/email/enrolment_approved-en.html
- templates/email/enrolment_approved-sv.html
- templates/email/enrolment_approved.html
PT-712. Cancellation process starts from enrolment approved message's cancellation link, so it needs to be included in notification template.
> Added cancellation links to enrolment approved messages.

- requirements.txt
Upgrade `drf-oidc-auth` dependency to make it compatible with new change from Tunnistamo
> PT-768 | Upgrade drf-oidc-auth

- templates/email/enrolment_summary-en.html
- templates/email/enrolment_summary-sv.html
- templates/email/enrolment_summary.html
Adding enrolment summary template
Screenshot:
> PT-736 | Add enrolment summary notification template

- occurrences/models.py
- occurrences/tests/test_models.py
PT-803. https://sentry.hel.ninja/aok/palvelutarjotin-api/issues/20121/
> Fixed a TypeError issue in group size calculation.

- occurrences/schema.py
> Occurrences minimum date is validated only when enrolment time is given.

- graphene_linked_events/schema.py
- graphene_linked_events/tests/test_api.py
- occurrences/schema.py
- occurrences/tests/snapshots/snap_test_api.py
- occurrences/tests/snapshots/snap_test_notifications.py
- occurrences/tests/test_api.py
- occurrences/tests/test_notifications.py
- I also update add event mutation to only allow auto_acceptance=false if and only if needed_occurrences=1
> PT-878 | Mass approvement and send message to multiple enrolments 

- occurrences/admin.py
PT-983. Improved list fields, list filters and search fields on occurrence and enrolment admin sites.
> Improvements to admin filters

- templates/sms/enrolment_approved.j2
- templates/sms/enrolment_declined.j2
- templates/sms/occurrence_cancelled.j2
PT-1002. While updating templates to the staging server, these came to my sight. They are already deployed / saved to staging database.
> Some critical fixes to sms notification templates.

- occurrences/utils.py
PT-1002. Added the missing trans closure to sms notifications.
> Added the missing trans function to SMS notifications.

- reports/templates/reports/admin/event_enrolments.html
- reports/views.py
PT-1025. Added 2 new columns to both report formats: html and csv.
> Added enrolment id and email contact info to events' enrolments report.

- occurrences/schema.py
- occurrences/tests/snapshots/snap_test_notifications.py
So extracting the custom message need to be moved outside of the for-loop 🤦
> PT-1033 | Fix mass approve mutation

- occurrences/models.py
- occurrences/tests/snapshots/snap_test_notifications.py
- occurrences/tests/test_notifications.py
PT-1014. When occurrence is cancelled, enrolments that are already cancelled or declined should not receive any messages.
> Occurrence cancellation notifications filtered.

- organisations/admin.py
- organisations/consts.py
- organisations/models.py
- organisations/notifications.py
- organisations/services.py
- organisations/tests/notification_template_fixtures.py
- organisations/tests/snapshots/snap_test_notifications.py
- organisations/tests/test_admin.py
- organisations/tests/test_notifications.py
- palvelutarjotin/settings.py
- templates/email/person_myprofile_accepted-en.html
- templates/email/person_myprofile_accepted-sv.html
- templates/email/person_myprofile_accepted.html
PT-1077. When a user has the is_staff -flag set to True and the person is linked to some organisations, when the user is updated from the user admin form, a notification will be sent.
Needs #180  and #181 as a base.
> A notification is sent to a person when his account is accepted

- organisations/schema.py
- organisations/tests/snapshots/snap_test_api.py
- organisations/tests/test_api.py
> Added a type filter for organisations GraphQL query.

- organisations/schema.py
- organisations/tests/snapshots/snap_test_api.py
- organisations/tests/test_api.py
> Disallowed organisation changes on update my profile mutation.

- organisations/admin.py
> Major fix to admin user change form when user has no person.

- organisations/admin.py
> Moved is_admin -field to the field set of advanced fields.

- occurrences/filters.py
- occurrences/schema.py
- occurrences/tests/snapshots/snap_test_api.py
- occurrences/tests/snapshots/snap_test_notifications.py
- occurrences/tests/test_api.py
PT-1050 PT-1105. Added a filter for cancelled status and palvelutarjotin event. Also added an orderBy order-filter.
> New occurrences-query filters and orderBy -variable

- organisations/admin.py
> Implemented a better applicant selector on organisation proposal admin form.

- occurrences/utils.py
In some cases the enrolment notification threw an UnboundLocalError.
> Trying to fix UnboundLocalError

- occurrences/models.py
- occurrences/tests/snapshots/snap_test_api.py
- occurrences/tests/test_api.py
- organisations/tests/snapshots/snap_test_notifications.py
Fixed the calculation of seats left in occurrence.
PT-1137 PT-1143.
The issue was: "Hyväksymättä" for pending seats is always zero.
> Fixed enrolments counting.

- occurrences/schema.py
- occurrences/tests/snapshots/snap_test_notifications.py
- occurrences/tests/test_api.py
> Skipping cancelled occurrences when resolving the next and the last occurrence

- occurrences/filters.py
- occurrences/tests/snapshots/snap_test_api.py
- occurrences/tests/snapshots/snap_test_notifications.py
- occurrences/tests/test_api.py
> Fix to upcoming occurrences filter when enrolment end days is null

- notification_importers/notification_importer.py
- notification_importers/tests/snapshots/snap_test_notification_file_importer.py
Small fix to regexp that searches the content of a title-element in a notification template.
PT-1171.
> Fixed a notification subject resolver.

- graphene_linked_events/rest_client.py
> Raised LinkedEvents timeout to 20s

- common/notification_service.py
> Added more logging to sms sending

- graphene_linked_events/schema.py
- graphene_linked_events/tests/snapshots/snap_test_api.py
- graphene_linked_events/tests/test_api.py
- requirements-dev.txt
This PR adds a query for fetching upcoming events.
> PT-1272 | Add GraphQL query for fetching upcoming events

- graphene_linked_events/schema.py
Passing the include parameter will allow fetching related resources with a single request.
Refs PT-1272
> PT-1272 | Pass include params with upcomingEvents

- reports/models.py
- reports/views.py
Added enrolment id to rehydration warning logging.
Added enrolment_time to view filters next to enrolment_start_time.
PT-1235. PT-1299.
> Improvements and fixes to enrolment reports

- occurrences/filters.py
- occurrences/schema.py
- occurrences/tests/snapshots/snap_test_api.py
- occurrences/tests/test_api.py
> Occurrence upcoming filter renamed to enrollable and new real upcoming filter added

- reports/models.py
- reports/serializers.py
- reports/tests/test_serializers.py
- reports/tests/test_utils.py
- reports/utils.py
> Added a Size2ArrayFieldBase serializer for "tuple fields"

- graphene_linked_events/schema.py
- graphene_linked_events/tests/snapshots/snap_test_api.py
- graphene_linked_events/tests/test_api.py
> New page centric meta data for upcoming occurrences schema

- occurrences/tests/test_api.py
- occurrences/tests/test_models.py
> Some code maintaining

- occurrences/admin.py
> Fixed the enrolment admin search

- reports/admin.py
> Fixed null pointer exception in enrolment admin get_sync_status

- occurrences/schema.py
- occurrences/tests/snapshots/snap_test_api.py
- occurrences/tests/test_api.py
> Fix to manually approved study groups enrolments capacity validation

- graphene_linked_events/rest_client.py
- graphene_linked_events/schema.py
- graphene_linked_events/tests/snapshots/snap_test_api.py
- graphene_linked_events/tests/test_api.py
- graphene_linked_events/tests/test_utils.py
- graphene_linked_events/utils.py
- reports/models.py
- reports/services.py
- reports/tests/test_models.py
- reports/tests/test_utils.py
- reports/utils.py
- requirements-dev.in
- requirements-dev.txt
- requirements-prod.in
- requirements-prod.txt
- requirements.in
- requirements.txt
This PR adds `nearbyPlaceId` and `nearbyDistance` arguments to the `events` query, which will allow searching for nearby events. PR also contains some refactoring for distance calculations after adding `geopy` to the requirements.
> PT-1289 | Search nearby events

- reports/admin.py
> Enrolment reports can be searched with a linked event id in admin view

- common/tests/json_fixtures.py
- occurrences/models.py
- occurrences/services.py
- occurrences/tests/test_notifications.py
> Handle the HTTP410 when sending an enrolment summary

- reports/serializers.py
- reports/tests/test_serializers.py
> Enrolment reports location information given in more detailed format

- reports/models.py
> Fixed enrolment reports none type enrolment logging

- CHANGELOG.md
- occurrences/event_api_services.py
- occurrences/schema.py
- occurrences/tests/snapshots/snap_test_api.py
> Places and events should not be fetched if there are no ids given

- common/utils.py
- graphene_linked_events/rest_client.py
- graphene_linked_events/schema.py
- graphene_linked_events/tests/test_api.py
- occurrences/services.py
Data source is required for the LinkedEvents production API to return any palvelutarjotin related events.
> PT-1506 | Event list requests to Linked events always include data source parameter

- organisations/admin.py
- organisations/models.py
PT-1514. Order the organisations by their name in the admin list filter
> Organisations ordered by name in the organisation filter

- organisations/admin.py
- organisations/models.py
- palvelutarjotin/settings.py
- reports/tests/test_views.py
- reports/views.py
- requirements.in
- requirements.txt
This PR adds a dropdown organisation filter to `PersonAdmin`. Also this PR bumps the Django version to the latest 3.2-bugfix release.
> PT-1514 | Add organisation filter to PersonAdmin

- organisations/admin.py
- reports/templates/reports/admin/persons.html
- reports/urls.py
- reports/views.py
PT-1515. Export persons in a HTML format and in a CSV format.
> Export persons from Person admin view

- .github/workflows/load_tests.yml
- .github/workflows/production.yml
- .github/workflows/review.yml
- .github/workflows/staging.yml
Set workflow concurrency [DEVOPS-429](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-429)
Load test is run after staging deployment is ready
> Set workflows concurrency

- .github/workflows/production.yml
- occurrences/tests/snapshots/snap_test_api.py
- occurrences/tests/snapshots/snap_test_notifications.py
[DEVOPS-444](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-444)
> Increase resource requirements on production environment 

- occurrences/schema.py
- occurrences/tests/test_api.py
PT-1542 PT-1548
Also refactored some old tests related to enrolments to clean the code.
> Disallow enrolling with an empty group

- organisations/models.py
- organisations/tests/test_models.py
Closes [PT-1621](https://helsinkisolutionoffice.atlassian.net/browse/PT-1621)
[PT-1621]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PT-1621]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix User deletion via queryset

- graphene_linked_events/tests/test_api.py
- organisations/admin.py
- palvelutarjotin/oidc.py
- palvelutarjotin/settings.py
- palvelutarjotin/tests/test_oidc.py
- reports/services.py
PT-1620.
Write the authentication timestamp to user's last_login -field on every 60 minutes.
> Save user's last activity if the configured interval has passed

- reports/models.py
- reports/tests/test_models.py
> Get a missing publisher from the report instances occurrence

- occurrences/schema.py
- occurrences/schema_services.py
- occurrences/tests/snapshots/snap_test_api.py
- occurrences/tests/test_api.py
> Allow enrolling to occurrence without notifications sending

- occurrences/admin.py
- occurrences/schema_services.py
- occurrences/tests/test_api.py
PT-1651.
Also cherry picked a commit for admin changes from #313.
> Fix the Event Queue Enrolment API save

- common/utils.py
- palvelutarjotin/settings.py
- palvelutarjotin/urls.py
> fix: review fixes for api/version PT-1652

- occurrences/tests/snapshots/snap_test_notifications.py
> test: update the snapshots

- palvelutarjotin/tests/test_oidc.py
Noticed that `test_authenticate` and
`test_authenticate_with_update_last_login_disabled` in `test_oidc.py`
were failing when changing from using `tunnistamo.test.kuva.hel.ninja`
to `tunnistamo.test.hel.ninja` in testing environments.
refs PT-1714 (noticed while working on this ticket)
[PT-1714](https://helsinkisolutionoffice.atlassian.net/browse/PT-1714)
[PT-1714]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: fix OIDC tests by setting token auth settings properly in tests

- .pre-commit-config.yaml
- graphene_linked_events/schema.py
- graphene_linked_events/tests/test_api.py
PT-1591.
Added keyword_OR_set1, keyword_OR_set2 and keyword_OR_set3 for the keywords of target groups, categories and activities / additional criterias.
>  add keyword_OR_set event query parameters

- graphene_linked_events/tests/test_api.py
> test: fix keyword_or_set test

- occurrences/admin.py
> fix: search_fields for study group

- README.md
Fix the empty commit d6b6f5324a6d98791b2bbb081f3747efefa10437 which didn't fix the commit a5cd2749eb5084ed3275ee1e9a464c5780223c6b. Also improved the instructions for linked events in the readme.md file PT-1726
> fix: slowness in the certain admin pages

- azure-pipelines-release.yml
- azure-pipelines-review.yml
- azure-pipelines-test.yml
- gdpr/models.py
- occurrences/tests/snapshots/snap_test_api.py
- occurrences/tests/snapshots/snap_test_notifications.py
PT-1758 PT-1763.
Fix syntax error.
> ci: fix config map

- graphene_linked_events/schema.py
PT-1796 PT-1798.
The admin UI event creation failed to fetch any keyword sets.
> fix: keyword set enum usage

- LICENSE
Update LICENSE year to current year of 2025
[PT-1877](https://helsinkisolutionoffice.atlassian.net/browse/PT-1877)
[PT-1877]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PT-1877 | Update `LICENSE` year to current year of 2025

- palvelutarjotin/urls.py
- sonar-project.properties
SonarCloud reliability/security hotspot related fixes,
please **see commit messages** for details.
[PT-1845](https://helsinkisolutionoffice.atlassian.net/browse/PT-1845)
[PT-1845]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PT-1845 | Still more SonarCloud fixes

- custom_health_checks/README.md
- custom_health_checks/apps.py
- custom_health_checks/backends.py
- custom_health_checks/tests/test_backends.py
- custom_health_checks/tests/test_healthz.py
- custom_health_checks/views.py
- palvelutarjotin/settings.py
- palvelutarjotin/urls.py
- requirements.in
- requirements.txt
PT-1848.
Copied implementation from Kummilapset and Notification Service:
- https://github.com/City-of-Helsinki/kukkuu/pull/442 
- https://github.com/City-of-Helsinki/notification-service-api/tree/master/custom_health_checks
> feat(health): improved health check to check database connection

- README.md
> docs: improve readme with architecture image and release & deployments

- palvelutarjotin/settings.py
> Fixes to admin site keycloak login and logout

- notification_importers/admin.py
Preview was prevented by CSP control.
> fix: csp rules for notification importers preview view

- .github/dependabot.yml
- CODEOWNERS
refs PT-1887 (palvelutarjotin)
refs RATYK-107 (similar changes in ratkaisutoimisto's projects)
[PT-1887](https://helsinkisolutionoffice.atlassian.net/browse/PT-1887)
[RATYK-107](https://helsinkisolutionoffice.atlassian.net/browse/RATYK-107)
[PT-1887]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RATYK-107]: https://helsinkisolutionoffice.atlassian.net/browse/RATYK-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PT-1887 | Replace dependabot reviewers with CODEOWNERS file
