- graphene_linked_events/schema.py
At the moment when trying to get event with include param only the last string of the array is effective. 
For example: When trying to get event with include param ["keyword", "audience"] -> only audience object is opened.
> Format include param to LinkedEvents event endpoint

- graphene_linked_events/schema.py
- palvelutarjotin/settings.py
Ideally the events endpoint should return events from logged in provider organisation. However it's not easy to do so with our current architecture (shared API key between provider account). In order to do that will require provider to authenticate both Palvelutarjotin in LinkedEvent which is not a good UX atm. So we decided to just restrict the events query to return only event with `data_source=palvelutarjotin`
> PT-230 | Only return linked events created by palvelutarjotin

- common/utils.py
- graphene_linked_events/schema.py
- graphene_linked_events/tests/test_api.py
- occurrences/models.py
`publisher` is a sub-organisation id created in linkedEvent which is now editable from API.
Publisher doesn’t not need to be provided through graphql argument but might be decided by user organisation selection since organsation has `publisher_id`
This field will be later used in events list filter to show events from user organisation only
Validation & authorization is out of the scope of this PR and will be implement later in a separated PR
> PT-267, PT-275 | Add organisation id to add/update event mutation

- graphene_linked_events/rest_client.py
- graphene_linked_events/schema.py
If user is staff, an authentication header will be added so user can be able to query draft events
Also added `showAll` argument to the query parameter to make draft events visible, and `publicationStatus` to filter event by `publication_status`
> PT-294 | Use APIKEY header in get query if user is staff, added showAll argument

- occurrences/schema.py
- occurrences/tests/snapshots/snap_test_api.py
- occurrences/tests/test_api.py
Update enrolment mutation will be used from Provider UI to modify enrolment (atm end-users are not allowed to modify their own enrolment because we don't require signed-in user to enrol occurrence)
> Update enrolment mutation

- graphene_linked_events/schema.py
Previously there is no way to know what happens with the API POST request to LinkedEvent if something went wrong. 
So I added a `resultText` field to the MutationResponse so frontend can know what is the reason behind a failed request. Also this message can be used to render error message if needed. Here is what it looks like
> PT-278 | Add result text to mutation response

- occurrences/models.py
- occurrences/tests/snapshots/snap_test_api.py
- occurrences/tests/test_api.py
By default, enrolment will have `pending` status. We should only count the number of seats taken by approved enrolment
> PT-370 | Only count seat taken by approved enrolment

- occurrences/models.py
- occurrences/signals.py
- occurrences/tests/snapshots/snap_test_notifications.py
- occurrences/tests/test_notifications.py
- occurrences/utils.py
Previously notification was sent to study group contact person. But now since enrolment itself has a contact-person, notification should be sent to this person instead of of study group contact person (though most of the time they are the same person). Only use study_group.person if enrolment person is not available (backward compatible)
> PT-377 | Sent notification to enrolment-contact-person if possible

- occurrences/schema.py
- occurrences/tests/snapshots/snap_test_api.py
- occurrences/tests/test_api.py
When approving a single enrolment, if this is a multl-occurrences event, all related enrolments of that study group to the same event should be approved as well
> PT-384 | Mass approve enrolment

- graphene_linked_events/utils.py
- occurrences/models.py
LinkedEvent API will return 404 for draft event if the query is from anonymous user so we would never get `publication_status` if it's a draft event.
Added an `is_staff` parameter to `get_event_data()` so when we want to get the `publication_status` we can use `is_staff` to always get the desired result.
> Fix publication status query

- graphene_linked_events/schema.py
- graphene_linked_events/tests/mock_data.py
- graphene_linked_events/tests/snapshots/snap_test_api.py
- graphene_linked_events/tests/test_api.py
- graphene_linked_events/utils.py
UI has a need of knowing which keyword set a keyword belongs to in order to assign it to correct box in edit event page.
We need seperated fields in the event query to do so.
- For keywords of TARGET_GROUPS keyword set => already assigned in native linked event field `audiences`
- For keywords of CATEGORIES keyword set => assign to our `categories` field
- For keywords of ADDITIONAL_CRITERIA keyword set => assign to our `additional_criteria` field
> PT-580 | Add categories and additional_criterial to event

- occurrences/schema.py
PT-735 UI will always send the captcha, and if it was not removed, it raised an error. Pop with None as default takes care of the issue.
> Improved captcha handler.

- graphene_linked_events/schema.py
- occurrences/models.py
- occurrences/schema.py
- occurrences/tests/snapshots/snap_test_api.py
- occurrences/tests/snapshots/snap_test_notifications.py
- occurrences/tests/test_api.py
- occurrences/tests/test_models.py
- occurrences/tests/test_notifications.py
Since location selector is moved to Step 2 in the new event creation wizard, it should be possible for FE to create draft event without location. GraphQL API should make this field optional in the mutation
> PT-942 | Make location optional in event mutations

- occurrences/schema.py
- occurrences/tests/snapshots/snap_test_notifications.py
- occurrences/tests/test_api.py
PT-934. As a provider when I mutate occurrence to API, it should validate the start time against enrolment
Enrolment summary enrolments are ordered by status to get same snapshot every time when running pytest.
NOTE: New design for occurrences could be waited before resolving this pull request, because it's been already talked that occurrence start and end time fields could be changing.  They should not affect on API, but who knows...
> Occurrence mutation should validate the start time against enrolment

- organisations/admin.py
- organisations/models.py
- organisations/tests/test_models.py
PT-994. Use username in user listing when name and email are not available
> Fixed user saving on admin site when there is no link to a person instance.

- organisations/admin.py
- palvelutarjotin/settings.py
- palvelutarjotin/urls.py
- reports/apps.py
- reports/templates/reports/admin/organisation_persons.html
- reports/tests/test_views.py
- reports/urls.py
- reports/views.py
PT-960. Organisations persons can be exported from admin site. They can be rendered using a new admin template that includes a table of all the persons with a joined_date or a CSV file could be created.
> As an admin I can export organisations persons

- occurrences/admin.py
- occurrences/templates/admin/palvelutarjotinevent_changelist.html
- reports/templates/reports/admin/event_enrolments.html
- reports/urls.py
- reports/views.py
PT-958. With new admin site actions, events enrolments can be viewed in admin site or exported to a CSV file.
NOTE: There are some dependencies. This is based on other PRs. Pull requests #148 and #149 should be merged first!
Admin report view in URL
/reports/palvelutarjotinevent/enrolments/
CSV can be imported from 
/reports/palvelutarjotinevent/enrolments/csv/
Parameters can be:
- ?ids=1,2,3,4
- ?start=2021-02-02
- ?start=2021-02-02&end=2021-05-03
- ?end=2021-05-03
> Exportable event enrolments stats on admin site

- palvelutarjotin/settings.py
- reports/tests/test_views.py
- reports/views.py
PT-1031.  Added ability to fetch events' enrolments report with global (graphene) id.
PT-997. Added unit tests for report views.
> Events' enrolments report can be filtered with global ids.

- graphene_linked_events/rest_client.py
PT-1043. New version of the LinkedEvents is using more aggressive cache. No-cache header could resolve the cache issues.
> Added no-cache header to LE rest-calls.

- graphene_linked_events/schema.py
PT-1044 Forcing the event type id to "general". Pull request #173 was to add a type id field to  the event schema, but there were problems with default_value used with required -attribute. More about that: https://github.com/graphql-python/graphene/commit/c08379ed85b2759de32777eb5dd3dca143a6d69f.
> Forced event type to general.

- graphene_linked_events/schema.py
Reverts City-of-Helsinki/palvelutarjotin#174
There were no use for this.
LinkedEvents team told that the test server and the production server are currently having a version that contains type_id in the Event model. They also told that after that version, it is needed to contain type_id in an event post and it should be in format {"type_id": "general"}. The type_id has been added in branch feature/event_type in commit 970d8ef607d600eb5fee84413ffacd25fc3fbb0b. In that version, **type_id is actually an enum, not a string!**. In that sense, we should post {"type_id": 1} instead. However, general type is also set to nullable in api (https://github.com/City-of-Helsinki/linkedevents/pull/459/files#diff-f645847ab170537ed98cb30203db3f05c21afd0c3b69fc2fd32a667f5f9b6e03R1364) and it's default in …
> Revert "Forced event type to general."

- reports/views.py
PT-1052. Set BOM and semicolon as a delimiter to fix the encoding issues.
Screenshot from Microsoft Excel for Mac:
FYI: 
- https://docs.python.org/3/library/csv.html
- https://stackoverflow.com/questions/5202648/adding-bom-unicode-signature-while-saving-file-in-python
- https://theonemanitdepartment.wordpress.com/2014/12/15/the-absolute-minimum-everyone-working-with-data-absolutely-positively-must-know-about-file-types-encoding-delimiters-and-data-types-no-excuses/
- https://en.wikipedia.org/wiki/Comma-separated_values
> Fixes to CSV file when reading it with Microsoft Excel

- organisations/admin.py
- organisations/services.py
- organisations/tests/snapshots/snap_test_notifications.py
- organisations/tests/test_admin.py
- organisations/tests/test_notifications.py
- reports/tests/test_views.py
PT-1090. Added a language field to person admin form.
Show only the users without  link to any person in person admin.
PT-1090
Added UserPersonInLine form to User admin change form.
PT-1090 Added person inline form in user change form, so it would be easier to find the person instance linked to the user.
Using admins and persons own language in my profile notifications.
PT-1090.
Changed the email is sent info message for admins.
PT-1096.
> Persons language is now editable in admin.

- graphene_linked_events/schema.py
- graphene_linked_events/tests/snapshots/snap_test_api.py
- graphene_linked_events/tests/test_api.py
- graphene_linked_events/utils.py
- occurrences/schema.py
- occurrences/signals.py
- occurrences/tests/test_signals.py
PT-1134 PT-1131. If LinkedEvents returns an event that does not match on any of our PalvelutarjotinEvent instance, an error was be raised. Now the resolve_events checks all the events in the response if they have a linked PalvelutarjotinEvent in our database.
Added some LinkedEvents API fail proof to occurrence signals.
> Fixing issues when the link fails between palvelutarjotin event and linked event's event

- graphene_linked_events/schema.py
- graphene_linked_events/tests/snapshots/snap_test_api.py
- graphene_linked_events/tests/test_api.py
LinkedEvents paginates the results, but Kultus API filters the paginated sets. This leads to a situation where the events count in meta data, easily does not match with the fact. If events.meta is used, the count is bigger than the filtered result. If a length of  integrated events is used, it would work only for unpaginated results. Using meta given by LinkedEvents is better, but can lead to empty pages!
PT-1170
Only ways to get the pagination work every time would be 
1. unpaginated result set from LE
2. Kultus includes a list of every tested event ids to the query.
We cannot do either! However, this solution introduced by this Pull request is better alternative than the current active one.
> Fix to events list meta count

- graphene_linked_events/schema.py
- graphene_linked_events/tests/test_api.py
all_ongoing_AND and all_ongoing_OR parameters triggers cache usage from LinkedEvents API. The LinkedEvent cache key includes the keywords name in 3 different languages, so when using all_ongoing_* -parameters, a free text search can be used to query keywords also.
PT-1144 PT-1205
> Support for event queries with all_ongoing_AND and all_ongoing_OR params

- .prod/uwsgi.ini
Healthcheck routes logging spams the production server logs, so they should be ignored. PT-1209.
> Don't log healthchecks in production.

- common/notification_service.py
- graphene_linked_events/rest_client.py
- neighborhood/rest_client.py
Without setting the timeout implicitly the timeout is set to None. Now it's set to 5 seconds on every requests that I found.
PT-1183.
> Added a timeout setting to all external requests

- servicemap/schema.py
- servicemap/tests/snapshots/snap_test_api.py
- servicemap/tests/test_api.py
- servicemap/utils.py
The service map API response with 1000+ schools and kindergartens, but the max page size is 1000. Because the service map's unit query does not support filtering with a search term and servicemap's search -query does not support filttering with service nodes, we needed a solution to return all the units (1000+) in a single page all at once. This is now achieved by returning all the pages from graphql API (with schoosAndKindergartensList -query). The next page is called recursively when one is available. 
PT-1234 PT-1298 PT-1312.
> Recursive rest-client call to fetch all schools and kindergarten pages at once

- graphene_linked_events/tests/snapshots/snap_test_api.py
- graphene_linked_events/tests/snapshots/snap_test_utils.py
- graphene_linked_events/tests/test_utils.py
- graphene_linked_events/utils.py
This PR fixes an issues where values in JSON responses were sanitized when only keys were supposed to be sanitized. E.g. email values should not have their `@` turned into `internal_` anymore.
> PT-1507 | Only sanitize keys in JSON responses from linked events

- occurrences/models.py
- occurrences/schema.py
- occurrences/tests/notification_template_fixtures.py
- occurrences/tests/snapshots/snap_test_api.py
- occurrences/tests/snapshots/snap_test_notifications.py
- occurrences/tests/test_api.py
- occurrences/tests/test_notifications.py
PT-1538. Preventing the SMS notification to be sent when enrolling to multiple occurrences at once and an error occurs after the first enrolment is handled. The transaction should and has rolled back, but the issue was in the SMS sending, which is sent via notification-service and the SMS notification was not rolled back.
This PR is done on the code formatting done in #274
> Send approval notifications after auto accepted enrolments are handled

- .github/workflows/production.yml
- .github/workflows/staging.yml
PT-1619.
The `delete-retention-period-exceeding-contact-info-cronjob`
was a too long name for a cronjob.
```
Error: CronJob.batch
"delete-retention-period-exceeding-contact-info-cronjob"
is invalid: metadata.name:
Invalid value: "delete-retention-period-exceeding-contact-info-cronjob":
must be no more than 52 characters.
```
> Fix a too long cronjob name

- graphene_linked_events/tests/test_api.py
- occurrences/tests/test_commands.py
- occurrences/tests/test_models.py
- organisations/tests/test_models.py
- reports/admin.py
- reports/models.py
- reports/services.py
PT-1525 PT-1527.
Add a has publisher filter to the enrolment reports admin page, because with that, it's easy to find the erroneous enrolment report entries and update them (using the admin actions).
Instead of throwing errors, just log them with a logger, so that more data is fetched. Instead of giving up when a first error occurs, we should try to fetch the rest of the info that is given. Also, an improvement to the logging was added, so that it's clearer where the issue is. It should also be noted that not all the places have coordinates, e.g. `helsinki:internet` for internet events, so we should not throw an KeyError in these cases, because it's a valid case.
> Improvements to the enrolment reports LinkedEvents-data hydration

- reports/services.py
Add support to resolve_place_divisions for the divisions being found directly in place_json["divisions"] and not necessarily always in place_json["location"]["divisions"].
resolve_place_divisions was refactored in
a9d530d1bb342bc20f077f6c5ae9f746257dc4ce but unfortunately the refactoring was done incorrectly.
A similar fix was done to resolve_place_coordinates in 234c113b7c8d7201cbc43f522bb62a5d174709da.
Refs PT-1620 (A similar fix to resolve_place_coordinates)
Refs PT-1525, PT-1527 (resolve_place_divisions was refactored)
> Add support to resolve_place_divisions for divisions not under location

- README.md
- Remove beta from Kultus API as it is in production already
- Add production environment's Kultus API URL
- Add info on how to obtain LinkedEvents configuration for testing
- Fix indentations
- Don't start text rows with a comma or a dot character
- Remove unnecessary URL namings where the plain URL works fine and
can't go out of sync with the name which is almost the same as the
URL
- Normalize LE / LinkedEvent / LinkedEvents text usage in README to
consistently use LinkedEvents
refs PT-1569 (setting up palvelutarjotin & palvelutarjotin-admin)
[PT-1569](https://helsinkisolutionoffice.atlassian.net/browse/PT-1569)
[PT-1569]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PT-1569 | update and clean up README

- README.md
- palvelutarjotin/tests/test_oidc.py
refs PT-1650
[PT-1650](https://helsinkisolutionoffice.atlassian.net/browse/PT-1650)
[PT-1650]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Tested that all tests pass:
- `docker-compose up`
- `docker exec -it kultus-backend bash`
- `pytest . -vv`
> PT-1650 | chore: switch from KuVa to Platta environments

- palvelutarjotin/settings.py
docker-compose up --build fails locally with:
```python
Traceback (most recent call last):
...
File "/app/palvelutarjotin/urls.py", line 12, in <module>
admin.site.index_title = " ".join([ugettext("Kultus API"),
get_api_version()])
File "/app/common/utils.py", line 49, in get_api_version
return " | ".join((__version__, settings.REVISION.decode("utf-8")))
AttributeError: 'str' object has no attribute 'decode'
```
get_api_version function assumes that REVISION has decode function:
```python
def get_api_version():
return " | ".join((__version__, settings.REVISION.decode("utf-8")))
```
so it makes sense that REVISION should be bytes, not str.
get_api_version is used to show the git hash of HEAD in the django admin site's title.
https://docs.python.org/3.9/library/subprocess.html documentation …
> fix git REVISION handling when git is unavailable

- occurrences/tests/test_models.py
- organisations/models.py
- organisations/tests/snapshots/snap_test_api.py
- organisations/tests/test_api.py
PT-1651 PT-1660.
1. Added some missing tests for Person
2. Added EventQueueEnrolments to the Django admin site
3. Show the person delete at -info in EventQueueEnrolment admin
4. Set the person delete at -info when a related person is deleted
> GDPR person deletion information to EventQueueEnrolment model instances

- graphene_linked_events/schema.py
- occurrences/event_api_services.py
- occurrences/models.py
- occurrences/schema.py
- occurrences/tests/mutations.py
- occurrences/tests/snapshots/snap_test_api.py
- occurrences/tests/test_api.py
- occurrences/tests/test_models.py
PT-1651 PT-1670.
The EventQueueEnrolments are meant to be transformable as Enrolments when the occurrence information is added to them. The old plan was to use the EnrolOccurrenceMutation to transform them, but when implementing the client for the mutation, it was clear that it was too complicated, since the EnrolOccurrenceMutation needs a new study group instance as an input. With this PickEnrolmentFromQueueMutation the ids can be used and the exact same study group will be used when the new enrolment is created.
> Add PickEnrolmentFromQueueMutation

- graphene_linked_events/schema.py
- occurrences/models.py
- occurrences/tests/test_models.py
PT-1213.
This pull request has been done as a base work for [PT-1213](https://helsinkisolutionoffice.atlassian.net/browse/PT-1213). The ticket was but on hold, because the amount of work was not giving enough.
However, the feature that was already implemented, could be good as so for some administrative use. It would be easier to find events related to some persons, for example when finding some GDPR related data.
Also, some refactoring (code splitting) is done to make the code more clear. The refactoring effects only to events query.
[PT-1213]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Filter events with contact info query

- notification_importers/templates/email/enrolment_summary_report-en.html
- notification_importers/templates/email/enrolment_summary_report-fi.html
- notification_importers/templates/email/enrolment_summary_report-sv.html
- notification_importers/tests/snapshots/snap_test_notification_file_importer.py
- occurrences/management/commands/send_enrolment_summary.py
- occurrences/models.py
- occurrences/notification_services.py
- occurrences/notifications.py
- occurrences/tests/snapshots/snap_test_notifications.py
- occurrences/tests/test_models.py
- occurrences/tests/test_notifications.py
PT-1717.
The enrolment summary now contains
1. a total new event queue enrolment count
2. event specific new queue enrolment count
Both of the new infos are only from events that are related to the recipient.
The `send_enrolment_summary_report_to_providers` is now removed
from the Enrolment model as a needless function.
It is replaced with an util that handles the both: the event specific
event queue enrolments and the event occurrence specific enrolments.
NOTE: The preview is viewable in `/admin/django_ilmoitin/notificationtemplate/` -change form
> feat: event queue enrolment counts are included in the enrolment summary

- occurrences/admin.py
The fix involved correcting the definition of certain form fields as readonly fields while designating others as autocomplete fields.
> Fix slowness in the certain admin pages

- palvelutarjotin/settings.py
- requirements.txt
PT-1758 PT-1763.
Upgraded the django-environ.
> fix: oidc audience env variable was always read as a string

- .prod/uwsgi.ini
PT-1758 PT-1763.
The Entra ID login needs a bigger buffer size because there are so many groups linked to the user.
> ci: increase uwsgi buffer size

- gdpr/service.py
- gdpr/tests/snapshots/snap_test_gdpr_api.py
- gdpr/tests/test_gdpr_api.py
- organisations/models.py
PT-1758.
The GDPR API deletion should change the user UUID, so a new link to service won't select the old account again.
This fixes the old implementation before the change in https://github.com/City-of-Helsinki/palvelutarjotin/pull/362
> fix: user deleted via GDPR API should not be relinkable to profile

- graphene_linked_events/schema.py
- graphene_linked_events/tests/test_api.py
- occurrences/admin.py
- occurrences/models.py
- occurrences/schema.py
- occurrences/tests/snapshots/snap_test_api.py
- occurrences/tests/test_models.py
PT-1668.
Also: 
- feat: occurrences are listed in inline component in palvelutarjotin event admin
- feat: improve the performance of admin site with auto complete fields and inline components
- refactor: move upcoming events annotation to query set. Add a new `with_next_occurrence` annotation to PalvelutarjotinEvent queryset
to do the job that was done in the upcoming events query endpoint.
> Resolve if pEvent has any spaces left for enrolment

- docker-compose.yml
The production stage of the Dockerfile can now be run with `DOCKER_TARGET=production docker compose up`. The production stage is exposed in a port 8000, so it also needs to be set available in the docker-compose configuration.
The development stage is available by default `docker compose up`, but also with DOCKER_TARGET by using `DOCKER_TARGET=development docker compose up`. 
To remove existing containers, use `docker compose down`. To rebuild a container use `--build`-flag, like `DOCKER_TARGET=production docker compose up --build`.
> chore: add DOCKER_TARGET and prod port to docker-compose config

- requirements.txt
PT-1796. Reference: KK-1246.
A proposed fix
https://github.com/City-of-Helsinki/django-ilmoitin/pull/42 was released in django-ilmoitin 0.7.1.
The missing migrations were applied to kukkuu with `python manage.py migrate`.
```
Running migrations:
Applying
django_ilmoitin.0006_alter_notificationtemplatetranslation_id... OK
Applying
django_ilmoitin.0007_alter_notificationtemplate_admins_to_notify... OK
```
> fix: upgrade django-ilmoitin to fix migration issues

- organisations/schema.py
- organisations/tests/test_api.py
A duplicate for https://github.com/City-of-Helsinki/palvelutarjotin/pull/370 with a shorter branch name, because it was an issue for infra.
----
PT-1804.
There are 2 kind of persons in the API: Those that acts as event
providers and are linked to some admin users, but also those that leads
a study group or makes an enrolment to the event. Both types are casted
as PersonNode, but only one of them has a user linked to it. However,
there is no case where we should currently include the deactivated user
instances, so those can always be excluded.
NOTE: After the authorization service is changed from the Tunnistamo to
the Helsinki Profile Keycloak, there will be duplicate user instances
for the admin users. Then, the clearest way to separate the old
Tunnistamo accounts from the active ones, is …
> Deactivated person should not be listed from API

- palvelutarjotin/consts.py
- palvelutarjotin/settings.py
- palvelutarjotin/tests/test_csp.py
- palvelutarjotin/urls.py
- requirements.in
- requirements.txt
PT-1874.
Add django-csp to requirements. Configure the CSP as centralized as possible. Refactor the GraphQL-path initialization aand wrap it with unsafe-inline CSP-rule.
> feat(csp): install and configure CSP-plugin

- common/tests/test_utils.py
- common/utils.py
- reports/services.py
- reports/views.py
PT-1909.
Remove port from the returned value of the `get_client_ip` -function.
Other miscallenous changes:
- fix a possible null pointer exception
- fix varaible typing
- refactor the writing of events approved enrolments CSV
> Fix remote address handling of manual access log audit logging

- .env.example
- palvelutarjotin/settings.py
PT-1830.
OIDC was already configured with django-helusers, but the Django Admin Keycloak authentication part was missing. Instructions for that could be found from django-helusers readme documentation:
https://github.com/City-of-Helsinki/django-helusers?tab=readme-ov-file#django-session-login.
Pipeline changes are done in Azure dev PR:
https://dev.azure.com/City-of-Helsinki/kultus/_git/kultus-pipelines/pullrequest/11506.
> chore: add environment variables for Keycloak auth

- README.md
Gruppo newsletter service was missing from README.
> docs: add gruppo to architecture README

- .prod/uwsgi.ini
- Dockerfile
- docker-entrypoint.sh
- requirements-prod.in
- requirements-prod.txt
Improve uWSGI options:
- Restart a worker after 1000 requests (max-requests)
- Restart a worker every hour (max-worker-lifetime)
- Restart a worker after 300MB resident memory usage (reload-on-rss)
- Restart a worker by force after 60 seconds (worker-reload-mercy)
- Use strict mode to catch unknown uWSGI options (strict)
- Require an application module to start (need-app)
- Avoid multiple interpreters (single-interpreter)
- Only use processes for concurrency, so only run one thread per
process
- Suppress errors about clients closing sockets
- Add Harakiri options
- Add Sentry-setup
- Add uwsgitop and settings
Refs: PT-1937
> PT-1937: uWGSI improvements

- .pre-commit-config.yaml
- Dockerfile
- common/utils.py
- palvelutarjotin/settings.py
- palvelutarjotin/urls.py
Git version history is not available in the container, so there's no commit hash to be fetched.
> Get commit hash from the Openshift environment

- reports/tests/test_views.py
- reports/views/csv_api.py
The logic for authenticating admin (staff) users was refactored previously. Along this users were migrated from using Django's is_staff to using a custom is_event_staff.
The ExportReportCsvView was not updated to reflect this change, which resulted in admin users receiving 403 errors when attempting to download CSV files.
refs: PT-1812, PT-1942
> fix: CSV endpoints incorrectly responding with 403

- occurrences/tests/test_commands.py
- organisations/models.py
- organisations/tests/test_models.py
Update person retention period deletion logic to return persons who:
1. Don't have a user account
2. Don't have any valid enrolments (either as person or study group contact)
3. Don't have any valid event queue enrolments
Add/update tests.
Refs: PT-1946
> PT-1946: Update person retention period deletion logic
